<?xml version="1.0" encoding="UTF-8" ?>
<Package name="11_Infoterminal" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="stylesheet" src="html/stylesheet.css" />
        <File name="adjust23" src="html/scripts/adjust23.js" />
        <File name="jquery-2.2.2.min" src="html/scripts/jquery-2.2.2.min.js" />
        <File name="jquery.qimhelpers" src="html/scripts/jquery.qimhelpers.js" />
        <File name="" src=".project" />
        <File name="jquery.mobile-1.4.5.min" src="html/scripts/jquery.mobile-1.4.5.min.js" />
        <File name="jquery.mobile.structure-1.4.5.min" src="html/scripts/jquery.mobile.structure-1.4.5.min.css" />
        <File name="memory" src="html/memory.css" />
        <File name="jquery.mobile-1.4.5.min" src="html/scripts/jquery.mobile-1.4.5.min.css" />
        <File name="memory" src="html/scripts/memory.js" />
        <File name="pepperController" src="html/scripts/pepperController.js" />
        <File name="snap.svg" src="html/scripts/snap.svg.js" />
        <File name="ttt" src="html/scripts/ttt.js" />
        <File name="ttt" src="html/ttt.css" />
        <File name="readmeHTML" src="readmeHTML.txt" />
        <File name="angular-animate" src="html/scripts/angular-animate.js" />
        <File name="angular.min" src="html/scripts/angular.min.js" />
        <File name="mainMemory" src="html/scripts/mainMemory.js" />
        <File name="mainTTT" src="html/scripts/mainTTT.js" />
        <File name="animHeart" src="html/bilder/animHeart.gif" />
        <File name="franziskanerVS" src="html/bilder/franziskanerVS.png" />
        <File name="home" src="html/bilder/home.png" />
        <File name="logoHFU" src="html/bilder/logoHFU.png" />
        <File name="logoMemory" src="html/bilder/logoMemory.png" />
        <File name="logoSpiel" src="html/bilder/logoSpiel.png" />
        <File name="logoTTT1" src="html/bilder/logoTTT1.png" />
        <File name="logoVS" src="html/bilder/logoVS.png" />
        <File name="pepperHead" src="html/bilder/pepperHead.png" />
        <File name="skylineVS" src="html/bilder/skylineVS.png" />
        <File name="wappenVS" src="html/bilder/wappenVS.png" />
        <File name="page02" src="html/page02.html" />
        <File name="page1112" src="html/page1112.html" />
        <File name="page01Controller" src="html/scripts/page01Controller.js" />
        <File name="page02" src="html/scripts/page02.js" />
        <File name="page02Controller" src="html/scripts/page02Controller.js" />
        <File name="page1111" src="html/scripts/page1111.js" />
        <File name="page1111Controller" src="html/scripts/page1111Controller.js" />
        <File name="page1112" src="html/scripts/page1112.js" />
        <File name="page1112Controller" src="html/scripts/page1112Controller.js" />
        <File name="VSbasic" src="html/themeVSbasic/VSbasic.css" />
        <File name="VSbasic.min" src="html/themeVSbasic/VSbasic.min.css" />
        <File name="ajax-loader" src="html/themeVSbasic/images/ajax-loader.gif" />
        <File name="action-black" src="html/themeVSbasic/images/icons-png/action-black.png" />
        <File name="action-white" src="html/themeVSbasic/images/icons-png/action-white.png" />
        <File name="alert-black" src="html/themeVSbasic/images/icons-png/alert-black.png" />
        <File name="alert-white" src="html/themeVSbasic/images/icons-png/alert-white.png" />
        <File name="arrow-d-black" src="html/themeVSbasic/images/icons-png/arrow-d-black.png" />
        <File name="arrow-d-l-black" src="html/themeVSbasic/images/icons-png/arrow-d-l-black.png" />
        <File name="arrow-d-l-white" src="html/themeVSbasic/images/icons-png/arrow-d-l-white.png" />
        <File name="arrow-d-r-black" src="html/themeVSbasic/images/icons-png/arrow-d-r-black.png" />
        <File name="arrow-d-r-white" src="html/themeVSbasic/images/icons-png/arrow-d-r-white.png" />
        <File name="arrow-d-white" src="html/themeVSbasic/images/icons-png/arrow-d-white.png" />
        <File name="arrow-l-black" src="html/themeVSbasic/images/icons-png/arrow-l-black.png" />
        <File name="arrow-l-white" src="html/themeVSbasic/images/icons-png/arrow-l-white.png" />
        <File name="arrow-r-black" src="html/themeVSbasic/images/icons-png/arrow-r-black.png" />
        <File name="arrow-r-white" src="html/themeVSbasic/images/icons-png/arrow-r-white.png" />
        <File name="arrow-u-black" src="html/themeVSbasic/images/icons-png/arrow-u-black.png" />
        <File name="arrow-u-l-black" src="html/themeVSbasic/images/icons-png/arrow-u-l-black.png" />
        <File name="arrow-u-l-white" src="html/themeVSbasic/images/icons-png/arrow-u-l-white.png" />
        <File name="arrow-u-r-black" src="html/themeVSbasic/images/icons-png/arrow-u-r-black.png" />
        <File name="arrow-u-r-white" src="html/themeVSbasic/images/icons-png/arrow-u-r-white.png" />
        <File name="arrow-u-white" src="html/themeVSbasic/images/icons-png/arrow-u-white.png" />
        <File name="audio-black" src="html/themeVSbasic/images/icons-png/audio-black.png" />
        <File name="audio-white" src="html/themeVSbasic/images/icons-png/audio-white.png" />
        <File name="back-black" src="html/themeVSbasic/images/icons-png/back-black.png" />
        <File name="back-white" src="html/themeVSbasic/images/icons-png/back-white.png" />
        <File name="bars-black" src="html/themeVSbasic/images/icons-png/bars-black.png" />
        <File name="bars-white" src="html/themeVSbasic/images/icons-png/bars-white.png" />
        <File name="bullets-black" src="html/themeVSbasic/images/icons-png/bullets-black.png" />
        <File name="bullets-white" src="html/themeVSbasic/images/icons-png/bullets-white.png" />
        <File name="calendar-black" src="html/themeVSbasic/images/icons-png/calendar-black.png" />
        <File name="calendar-white" src="html/themeVSbasic/images/icons-png/calendar-white.png" />
        <File name="camera-black" src="html/themeVSbasic/images/icons-png/camera-black.png" />
        <File name="camera-white" src="html/themeVSbasic/images/icons-png/camera-white.png" />
        <File name="carat-d-black" src="html/themeVSbasic/images/icons-png/carat-d-black.png" />
        <File name="carat-d-white" src="html/themeVSbasic/images/icons-png/carat-d-white.png" />
        <File name="carat-l-black" src="html/themeVSbasic/images/icons-png/carat-l-black.png" />
        <File name="carat-l-white" src="html/themeVSbasic/images/icons-png/carat-l-white.png" />
        <File name="carat-r-black" src="html/themeVSbasic/images/icons-png/carat-r-black.png" />
        <File name="carat-r-white" src="html/themeVSbasic/images/icons-png/carat-r-white.png" />
        <File name="carat-u-black" src="html/themeVSbasic/images/icons-png/carat-u-black.png" />
        <File name="carat-u-white" src="html/themeVSbasic/images/icons-png/carat-u-white.png" />
        <File name="check-black" src="html/themeVSbasic/images/icons-png/check-black.png" />
        <File name="check-white" src="html/themeVSbasic/images/icons-png/check-white.png" />
        <File name="clock-black" src="html/themeVSbasic/images/icons-png/clock-black.png" />
        <File name="clock-white" src="html/themeVSbasic/images/icons-png/clock-white.png" />
        <File name="cloud-black" src="html/themeVSbasic/images/icons-png/cloud-black.png" />
        <File name="cloud-white" src="html/themeVSbasic/images/icons-png/cloud-white.png" />
        <File name="comment-black" src="html/themeVSbasic/images/icons-png/comment-black.png" />
        <File name="comment-white" src="html/themeVSbasic/images/icons-png/comment-white.png" />
        <File name="delete-black" src="html/themeVSbasic/images/icons-png/delete-black.png" />
        <File name="delete-white" src="html/themeVSbasic/images/icons-png/delete-white.png" />
        <File name="edit-black" src="html/themeVSbasic/images/icons-png/edit-black.png" />
        <File name="edit-white" src="html/themeVSbasic/images/icons-png/edit-white.png" />
        <File name="eye-black" src="html/themeVSbasic/images/icons-png/eye-black.png" />
        <File name="eye-white" src="html/themeVSbasic/images/icons-png/eye-white.png" />
        <File name="forbidden-black" src="html/themeVSbasic/images/icons-png/forbidden-black.png" />
        <File name="forbidden-white" src="html/themeVSbasic/images/icons-png/forbidden-white.png" />
        <File name="forward-black" src="html/themeVSbasic/images/icons-png/forward-black.png" />
        <File name="forward-white" src="html/themeVSbasic/images/icons-png/forward-white.png" />
        <File name="gear-black" src="html/themeVSbasic/images/icons-png/gear-black.png" />
        <File name="gear-white" src="html/themeVSbasic/images/icons-png/gear-white.png" />
        <File name="grid-black" src="html/themeVSbasic/images/icons-png/grid-black.png" />
        <File name="grid-white" src="html/themeVSbasic/images/icons-png/grid-white.png" />
        <File name="heart-black" src="html/themeVSbasic/images/icons-png/heart-black.png" />
        <File name="heart-white" src="html/themeVSbasic/images/icons-png/heart-white.png" />
        <File name="home-black" src="html/themeVSbasic/images/icons-png/home-black.png" />
        <File name="home-white" src="html/themeVSbasic/images/icons-png/home-white.png" />
        <File name="info-black" src="html/themeVSbasic/images/icons-png/info-black.png" />
        <File name="info-white" src="html/themeVSbasic/images/icons-png/info-white.png" />
        <File name="location-black" src="html/themeVSbasic/images/icons-png/location-black.png" />
        <File name="location-white" src="html/themeVSbasic/images/icons-png/location-white.png" />
        <File name="lock-black" src="html/themeVSbasic/images/icons-png/lock-black.png" />
        <File name="lock-white" src="html/themeVSbasic/images/icons-png/lock-white.png" />
        <File name="mail-black" src="html/themeVSbasic/images/icons-png/mail-black.png" />
        <File name="mail-white" src="html/themeVSbasic/images/icons-png/mail-white.png" />
        <File name="minus-black" src="html/themeVSbasic/images/icons-png/minus-black.png" />
        <File name="minus-white" src="html/themeVSbasic/images/icons-png/minus-white.png" />
        <File name="navigation-black" src="html/themeVSbasic/images/icons-png/navigation-black.png" />
        <File name="navigation-white" src="html/themeVSbasic/images/icons-png/navigation-white.png" />
        <File name="phone-black" src="html/themeVSbasic/images/icons-png/phone-black.png" />
        <File name="phone-white" src="html/themeVSbasic/images/icons-png/phone-white.png" />
        <File name="plus-black" src="html/themeVSbasic/images/icons-png/plus-black.png" />
        <File name="plus-white" src="html/themeVSbasic/images/icons-png/plus-white.png" />
        <File name="power-black" src="html/themeVSbasic/images/icons-png/power-black.png" />
        <File name="power-white" src="html/themeVSbasic/images/icons-png/power-white.png" />
        <File name="recycle-black" src="html/themeVSbasic/images/icons-png/recycle-black.png" />
        <File name="recycle-white" src="html/themeVSbasic/images/icons-png/recycle-white.png" />
        <File name="refresh-black" src="html/themeVSbasic/images/icons-png/refresh-black.png" />
        <File name="refresh-white" src="html/themeVSbasic/images/icons-png/refresh-white.png" />
        <File name="search-black" src="html/themeVSbasic/images/icons-png/search-black.png" />
        <File name="search-white" src="html/themeVSbasic/images/icons-png/search-white.png" />
        <File name="shop-black" src="html/themeVSbasic/images/icons-png/shop-black.png" />
        <File name="shop-white" src="html/themeVSbasic/images/icons-png/shop-white.png" />
        <File name="star-black" src="html/themeVSbasic/images/icons-png/star-black.png" />
        <File name="star-white" src="html/themeVSbasic/images/icons-png/star-white.png" />
        <File name="tag-black" src="html/themeVSbasic/images/icons-png/tag-black.png" />
        <File name="tag-white" src="html/themeVSbasic/images/icons-png/tag-white.png" />
        <File name="user-black" src="html/themeVSbasic/images/icons-png/user-black.png" />
        <File name="user-white" src="html/themeVSbasic/images/icons-png/user-white.png" />
        <File name="video-black" src="html/themeVSbasic/images/icons-png/video-black.png" />
        <File name="video-white" src="html/themeVSbasic/images/icons-png/video-white.png" />
        <File name="jquery.mobile.icons.min" src="html/themeVSbasic/jquery.mobile.icons.min.css" />
        <File name="material" src="material.pptx" />
        <File name="skylineVSsmall" src="html/bilder/skylineVSsmall.png" />
        <File name="main" src="html/scripts/main.js" />
        <File name="page01Controller_test" src="html/scripts/page01Controller_test.js" />
        <File name="index" src="html/index.html" />
        <File name="mute" src="html/bilder/mute.png" />
        <File name="muteGrey" src="html/bilder/muteGrey.png" />
        <File name="unmute" src="html/bilder/unmute.png" />
        <File name="unmuteGrey" src="html/bilder/unmuteGrey.png" />
        <File name="volMinus" src="html/bilder/volMinus.png" />
        <File name="volPlus" src="html/bilder/volPlus.png" />
        <File name="StandBehaviors" src="StandBehaviors.txt" />
        <File name="epicsax" src="behavior_1/epicsax.ogg" />
        <File name="galerieVS" src="html/bilder/galerieVS.png" />
        <File name="urlGallerie" src="html/bilder/urlGallerie.png" />
        <File name="page1111" src="html/page1111.html" />
        <File name="tttPage" src="html/tttPage.html" />
        <File name="logo1HFU" src="html/bilder/logo1HFU.png" />
        <File name="memoryPage" src="html/memoryPage.html" />
        <File name="pageHFU" src="html/pageHFU.html" />
        <File name="pageHFU" src="html/scripts/pageHFU.js" />
        <File name="pageHFUController" src="html/scripts/pageHFUController.js" />
        <File name="slideshow" src="html/slideshow.html" />
        <File name="HFU_BlackForest" src="html/themeBlackForest/HFU_BlackForest.css" />
        <File name="HFU_BlackForest.min" src="html/themeBlackForest/HFU_BlackForest.min.css" />
        <File name="ajax-loader" src="html/themeBlackForest/images/ajax-loader.gif" />
        <File name="action-black" src="html/themeBlackForest/images/icons-png/action-black.png" />
        <File name="action-white" src="html/themeBlackForest/images/icons-png/action-white.png" />
        <File name="alert-black" src="html/themeBlackForest/images/icons-png/alert-black.png" />
        <File name="alert-white" src="html/themeBlackForest/images/icons-png/alert-white.png" />
        <File name="arrow-d-black" src="html/themeBlackForest/images/icons-png/arrow-d-black.png" />
        <File name="arrow-d-l-black" src="html/themeBlackForest/images/icons-png/arrow-d-l-black.png" />
        <File name="arrow-d-l-white" src="html/themeBlackForest/images/icons-png/arrow-d-l-white.png" />
        <File name="arrow-d-r-black" src="html/themeBlackForest/images/icons-png/arrow-d-r-black.png" />
        <File name="arrow-d-r-white" src="html/themeBlackForest/images/icons-png/arrow-d-r-white.png" />
        <File name="arrow-d-white" src="html/themeBlackForest/images/icons-png/arrow-d-white.png" />
        <File name="arrow-l-black" src="html/themeBlackForest/images/icons-png/arrow-l-black.png" />
        <File name="arrow-l-white" src="html/themeBlackForest/images/icons-png/arrow-l-white.png" />
        <File name="arrow-r-black" src="html/themeBlackForest/images/icons-png/arrow-r-black.png" />
        <File name="arrow-r-white" src="html/themeBlackForest/images/icons-png/arrow-r-white.png" />
        <File name="arrow-u-black" src="html/themeBlackForest/images/icons-png/arrow-u-black.png" />
        <File name="arrow-u-l-black" src="html/themeBlackForest/images/icons-png/arrow-u-l-black.png" />
        <File name="arrow-u-l-white" src="html/themeBlackForest/images/icons-png/arrow-u-l-white.png" />
        <File name="arrow-u-r-black" src="html/themeBlackForest/images/icons-png/arrow-u-r-black.png" />
        <File name="arrow-u-r-white" src="html/themeBlackForest/images/icons-png/arrow-u-r-white.png" />
        <File name="arrow-u-white" src="html/themeBlackForest/images/icons-png/arrow-u-white.png" />
        <File name="audio-black" src="html/themeBlackForest/images/icons-png/audio-black.png" />
        <File name="audio-white" src="html/themeBlackForest/images/icons-png/audio-white.png" />
        <File name="back-black" src="html/themeBlackForest/images/icons-png/back-black.png" />
        <File name="back-white" src="html/themeBlackForest/images/icons-png/back-white.png" />
        <File name="bars-black" src="html/themeBlackForest/images/icons-png/bars-black.png" />
        <File name="bars-white" src="html/themeBlackForest/images/icons-png/bars-white.png" />
        <File name="bullets-black" src="html/themeBlackForest/images/icons-png/bullets-black.png" />
        <File name="bullets-white" src="html/themeBlackForest/images/icons-png/bullets-white.png" />
        <File name="calendar-black" src="html/themeBlackForest/images/icons-png/calendar-black.png" />
        <File name="calendar-white" src="html/themeBlackForest/images/icons-png/calendar-white.png" />
        <File name="camera-black" src="html/themeBlackForest/images/icons-png/camera-black.png" />
        <File name="camera-white" src="html/themeBlackForest/images/icons-png/camera-white.png" />
        <File name="carat-d-black" src="html/themeBlackForest/images/icons-png/carat-d-black.png" />
        <File name="carat-d-white" src="html/themeBlackForest/images/icons-png/carat-d-white.png" />
        <File name="carat-l-black" src="html/themeBlackForest/images/icons-png/carat-l-black.png" />
        <File name="carat-l-white" src="html/themeBlackForest/images/icons-png/carat-l-white.png" />
        <File name="carat-r-black" src="html/themeBlackForest/images/icons-png/carat-r-black.png" />
        <File name="carat-r-white" src="html/themeBlackForest/images/icons-png/carat-r-white.png" />
        <File name="carat-u-black" src="html/themeBlackForest/images/icons-png/carat-u-black.png" />
        <File name="carat-u-white" src="html/themeBlackForest/images/icons-png/carat-u-white.png" />
        <File name="check-black" src="html/themeBlackForest/images/icons-png/check-black.png" />
        <File name="check-white" src="html/themeBlackForest/images/icons-png/check-white.png" />
        <File name="clock-black" src="html/themeBlackForest/images/icons-png/clock-black.png" />
        <File name="clock-white" src="html/themeBlackForest/images/icons-png/clock-white.png" />
        <File name="cloud-black" src="html/themeBlackForest/images/icons-png/cloud-black.png" />
        <File name="cloud-white" src="html/themeBlackForest/images/icons-png/cloud-white.png" />
        <File name="comment-black" src="html/themeBlackForest/images/icons-png/comment-black.png" />
        <File name="comment-white" src="html/themeBlackForest/images/icons-png/comment-white.png" />
        <File name="delete-black" src="html/themeBlackForest/images/icons-png/delete-black.png" />
        <File name="delete-white" src="html/themeBlackForest/images/icons-png/delete-white.png" />
        <File name="edit-black" src="html/themeBlackForest/images/icons-png/edit-black.png" />
        <File name="edit-white" src="html/themeBlackForest/images/icons-png/edit-white.png" />
        <File name="eye-black" src="html/themeBlackForest/images/icons-png/eye-black.png" />
        <File name="eye-white" src="html/themeBlackForest/images/icons-png/eye-white.png" />
        <File name="forbidden-black" src="html/themeBlackForest/images/icons-png/forbidden-black.png" />
        <File name="forbidden-white" src="html/themeBlackForest/images/icons-png/forbidden-white.png" />
        <File name="forward-black" src="html/themeBlackForest/images/icons-png/forward-black.png" />
        <File name="forward-white" src="html/themeBlackForest/images/icons-png/forward-white.png" />
        <File name="gear-black" src="html/themeBlackForest/images/icons-png/gear-black.png" />
        <File name="gear-white" src="html/themeBlackForest/images/icons-png/gear-white.png" />
        <File name="grid-black" src="html/themeBlackForest/images/icons-png/grid-black.png" />
        <File name="grid-white" src="html/themeBlackForest/images/icons-png/grid-white.png" />
        <File name="heart-black" src="html/themeBlackForest/images/icons-png/heart-black.png" />
        <File name="heart-white" src="html/themeBlackForest/images/icons-png/heart-white.png" />
        <File name="home-black" src="html/themeBlackForest/images/icons-png/home-black.png" />
        <File name="home-white" src="html/themeBlackForest/images/icons-png/home-white.png" />
        <File name="info-black" src="html/themeBlackForest/images/icons-png/info-black.png" />
        <File name="info-white" src="html/themeBlackForest/images/icons-png/info-white.png" />
        <File name="location-black" src="html/themeBlackForest/images/icons-png/location-black.png" />
        <File name="location-white" src="html/themeBlackForest/images/icons-png/location-white.png" />
        <File name="lock-black" src="html/themeBlackForest/images/icons-png/lock-black.png" />
        <File name="lock-white" src="html/themeBlackForest/images/icons-png/lock-white.png" />
        <File name="mail-black" src="html/themeBlackForest/images/icons-png/mail-black.png" />
        <File name="mail-white" src="html/themeBlackForest/images/icons-png/mail-white.png" />
        <File name="minus-black" src="html/themeBlackForest/images/icons-png/minus-black.png" />
        <File name="minus-white" src="html/themeBlackForest/images/icons-png/minus-white.png" />
        <File name="navigation-black" src="html/themeBlackForest/images/icons-png/navigation-black.png" />
        <File name="navigation-white" src="html/themeBlackForest/images/icons-png/navigation-white.png" />
        <File name="phone-black" src="html/themeBlackForest/images/icons-png/phone-black.png" />
        <File name="phone-white" src="html/themeBlackForest/images/icons-png/phone-white.png" />
        <File name="plus-black" src="html/themeBlackForest/images/icons-png/plus-black.png" />
        <File name="plus-white" src="html/themeBlackForest/images/icons-png/plus-white.png" />
        <File name="power-black" src="html/themeBlackForest/images/icons-png/power-black.png" />
        <File name="power-white" src="html/themeBlackForest/images/icons-png/power-white.png" />
        <File name="recycle-black" src="html/themeBlackForest/images/icons-png/recycle-black.png" />
        <File name="recycle-white" src="html/themeBlackForest/images/icons-png/recycle-white.png" />
        <File name="refresh-black" src="html/themeBlackForest/images/icons-png/refresh-black.png" />
        <File name="refresh-white" src="html/themeBlackForest/images/icons-png/refresh-white.png" />
        <File name="search-black" src="html/themeBlackForest/images/icons-png/search-black.png" />
        <File name="search-white" src="html/themeBlackForest/images/icons-png/search-white.png" />
        <File name="shop-black" src="html/themeBlackForest/images/icons-png/shop-black.png" />
        <File name="shop-white" src="html/themeBlackForest/images/icons-png/shop-white.png" />
        <File name="star-black" src="html/themeBlackForest/images/icons-png/star-black.png" />
        <File name="star-white" src="html/themeBlackForest/images/icons-png/star-white.png" />
        <File name="tag-black" src="html/themeBlackForest/images/icons-png/tag-black.png" />
        <File name="tag-white" src="html/themeBlackForest/images/icons-png/tag-white.png" />
        <File name="user-black" src="html/themeBlackForest/images/icons-png/user-black.png" />
        <File name="user-white" src="html/themeBlackForest/images/icons-png/user-white.png" />
        <File name="video-black" src="html/themeBlackForest/images/icons-png/video-black.png" />
        <File name="video-white" src="html/themeBlackForest/images/icons-png/video-white.png" />
        <File name="jquery.mobile.icons.min" src="html/themeBlackForest/jquery.mobile.icons.min.css" />
        <File name="memory.js" src="html/scripts/memory.js.org" />
        <File name="beep" src="behavior_1/sounds/beep.wav" />
        <File name="clickOn" src="behavior_1/sounds/clickOn.wav" />
        <File name="pling" src="behavior_1/sounds/pling.mp3" />
        <File name="pling" src="behavior_1/sounds/pling.wav" />
        <File name="slurp" src="behavior_1/sounds/slurp.wav" />
        <File name="toggle" src="behavior_1/sounds/toggle.wav" />
        <File name="studiumAIN" src="html/bilder/studiumAIN.png" />
        <File name="studiumINM" src="html/bilder/studiumINM.png" />
        <File name="studiumITP" src="html/bilder/studiumITP.png" />
        <File name="studiumMOS" src="html/bilder/studiumMOS.png" />
        <File name="informatikClip" src="html/bilder/informatikClip.mp4" />
        <File name="swipeL2R" src="behavior_1/sounds/swipeL2R.wav" />
        <File name="swipeR2L" src="behavior_1/sounds/swipeR2L.wav" />
        <File name="Folie3" src="html/bilder/Folie3.png" />
        <File name="Folie4" src="html/bilder/Folie4.png" />
        <File name="Folie5" src="html/bilder/Folie5.png" />
        <File name="drop" src="behavior_1/sounds/drop.wav" />
        <File name="VillingenSchwenningenClip" src="html/bilder/VillingenSchwenningenClip.mp4" />
        <File name="html" src="html.zip" />
    </Resources>
    <Topics />
    <IgnoredPaths />
    <Translations auto-fill="de_DE">
        <Translation name="translation_de_DE" src="translations/translation_de_DE.ts" language="de_DE" />
    </Translations>
</Package>
