<?xml version="1.0" encoding="UTF-8" ?>
<Package name="11_Infoterminal" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="" src=".project" />
        <File name="readmeHTML" src="readmeHTML.txt" />
        <File name="material" src="material.pptx" />
        <File name="StandBehaviors" src="StandBehaviors.txt" />
        <File name="epicsax" src="behavior_1/epicsax.ogg" />
        <File name="beep" src="behavior_1/sounds/beep.wav" />
        <File name="clickOn" src="behavior_1/sounds/clickOn.wav" />
        <File name="pling" src="behavior_1/sounds/pling.mp3" />
        <File name="pling" src="behavior_1/sounds/pling.wav" />
        <File name="slurp" src="behavior_1/sounds/slurp.wav" />
        <File name="toggle" src="behavior_1/sounds/toggle.wav" />
        <File name="swipeL2R" src="behavior_1/sounds/swipeL2R.wav" />
        <File name="swipeR2L" src="behavior_1/sounds/swipeR2L.wav" />
        <File name="drop" src="behavior_1/sounds/drop.wav" />
        <File name="buergersaal_furtwangen" src="html/assets/images/buergersaal_furtwangen.jpg" />
        <File name="museum_gasthaus_arche_furtwangen" src="html/assets/images/museum_gasthaus_arche_furtwangen.jpg" />
        <File name="roesslekeller_neukirch" src="html/assets/images/roesslekeller_neukirch.jpg" />
        <File name="pepper_head" src="html/assets/pepper_head.svg" />
        <File name="uhrenmuseum" src="html/assets/uhrenmuseum.jpg" />
        <File name="furtwangen" src="html/assets/images/furtwangen.jpg" />
        <File name="museum_gasthaus_arche" src="html/assets/museum_gasthaus_arche.jpeg" />
        <File name="rathaus_image" src="html/assets/rathaus_image.jpg" />
        <File name="buergersaal_furtwangen1" src="html/assets/images/buergersaal_furtwangen1.jpg" />
        <File name="rathaus_image1" src="html/assets/rathaus_image1.jpg" />
        <File name="museum_gasthaus_arche_furtwangen original" src="html/assets/images/museum_gasthaus_arche_furtwangen original.jpg" />
        <File name="roesslekeller_neukirch original" src="html/assets/images/roesslekeller_neukirch original.jpg" />
        <File name="card_background" src="html/assets/backgrounds/card_background.jpg" />
        <File name="furtwangen_background" src="html/assets/backgrounds/furtwangen_background.jpg" />
        <File name="settings_background" src="html/assets/backgrounds/settings_background.jpg" />
        <File name="brend_turm" src="html/assets/brend_turm.jpg" />
        <File name="donauquelle" src="html/assets/donauquelle.jpg" />
        <File name="Roboto" src="html/assets/fonts/Roboto.css" />
        <File name="Roboto2" src="html/assets/fonts/Roboto2.css" />
        <File name="Roboto3" src="html/assets/fonts/Roboto3.css" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmQiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmQiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmUiAo" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmUiAo.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmXiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmXiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmYiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmYiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmZiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmZiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmaiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmaiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmbiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalmbiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaaln6iArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaaln6iArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalnoiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYaalnoiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmQiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmQiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmUiAo" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmUiAo.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmXiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmXiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmYiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmYiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmZiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmZiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmaiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmaiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmbiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmbiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjaln6iArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjaln6iArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalnoiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalnoiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmQiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmQiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmUiAo" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmUiAo.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmXiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmXiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmYiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmYiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmZiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmZiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmaiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmaiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmbiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVmbiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVn6iArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVn6iArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVnoiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabVnoiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmQiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmQiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmUiAo" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmUiAo.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmXiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmXiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmYiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmYiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmZiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmZiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmaiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmaiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmbiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVmbiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVn6iArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVn6iArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVnoiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWub2bVnoiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmQiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmQiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmUiAo" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmUiAo.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmXiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmXiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmYiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmYiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmZiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmZiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmaiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmaiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmbiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVmbiArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVn6iArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVn6iArmlw.woff2" />
        <File name="KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVnoiArmlw" src="html/assets/fonts/woffFiles/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbVnoiArmlw.woff2" />
        <File name="furtwangen_badge" src="html/assets/furtwangen_badge.svg" />
        <File name="furtwangen_logo" src="html/assets/furtwangen_logo.svg" />
        <File name="furtwangen_logo_outline" src="html/assets/furtwangen_logo_outline.svg" />
        <File name="guenterfelsen original" src="html/assets/guenterfelsen original.jpg" />
        <File name="guenterfelsen" src="html/assets/guenterfelsen.jpg" />
        <File name="arrow_left" src="html/assets/icons/arrow_left.svg" />
        <File name="arrow_right" src="html/assets/icons/arrow_right.svg" />
        <File name="book_open" src="html/assets/icons/book_open.svg" />
        <File name="brain" src="html/assets/icons/brain.svg" />
        <File name="buergersaal-icon" src="html/assets/icons/buergersaal-icon.svg" />
        <File name="camera_on_rectangle" src="html/assets/icons/camera_on_rectangle.svg" />
        <File name="clock" src="html/assets/icons/clock.svg" />
        <File name="coffee" src="html/assets/icons/coffee.svg" />
        <File name="custom_map_1" src="html/assets/icons/custom_map_1.svg" />
        <File name="custom_map_2" src="html/assets/icons/custom_map_2.svg" />
        <File name="design" src="html/assets/icons/design.svg" />
        <File name="fitness" src="html/assets/icons/fitness.svg" />
        <File name="game_controller" src="html/assets/icons/game_controller.svg" />
        <File name="game_controller_left" src="html/assets/icons/game_controller_left.svg" />
        <File name="game_controller_right" src="html/assets/icons/game_controller_right.svg" />
        <File name="graduate_cap" src="html/assets/icons/graduate_cap.svg" />
        <File name="hfu" src="html/assets/icons/hfu.svg" />
        <File name="home" src="html/assets/icons/home.svg" />
        <File name="international" src="html/assets/icons/international.svg" />
        <File name="mappin" src="html/assets/icons/mappin.svg" />
        <File name="menu" src="html/assets/icons/menu.svg" />
        <File name="mountain" src="html/assets/icons/mountain.svg" />
        <File name="museum-icon" src="html/assets/icons/museum-icon.svg" />
        <File name="museum" src="html/assets/icons/museum.svg" />
        <File name="outdoor" src="html/assets/icons/outdoor.svg" />
        <File name="pepper_head" src="html/assets/icons/pepper_head.png" />
        <File name="person" src="html/assets/icons/person.svg" />
        <File name="questionmark_diamond" src="html/assets/icons/questionmark_diamond.svg" />
        <File name="questionmark_folder" src="html/assets/icons/questionmark_folder.svg" />
        <File name="refresh" src="html/assets/icons/refresh.svg" />
        <File name="repeat" src="html/assets/icons/repeat.svg" />
        <File name="restaurant" src="html/assets/icons/restaurant.svg" />
        <File name="rocks" src="html/assets/icons/rocks.svg" />
        <File name="roessle-icon" src="html/assets/icons/roessle-icon.svg" />
        <File name="settings" src="html/assets/icons/settings.svg" />
        <File name="ski" src="html/assets/icons/ski.svg" />
        <File name="square_grid_3x3" src="html/assets/icons/square_grid_3x3.svg" />
        <File name="stop-button" src="html/assets/icons/stop-button.png" />
        <File name="university" src="html/assets/icons/university.svg" />
        <File name="volume_down" src="html/assets/icons/volume_down.svg" />
        <File name="volume_mute" src="html/assets/icons/volume_mute.svg" />
        <File name="volume_on" src="html/assets/icons/volume_on.png" />
        <File name="volume_up" src="html/assets/icons/volume_up.svg" />
        <File name="walk" src="html/assets/icons/walk.svg" />
        <File name="water_drop" src="html/assets/icons/water_drop.svg" />
        <File name="speedDial" src="html/components/speedDial/speedDial.css" />
        <File name="speedDial" src="html/components/speedDial/speedDial.html" />
        <File name="speedDial" src="html/components/speedDial/speedDial.js" />
        <File name="index" src="html/index.html" />
        <File name="citizenOffice" src="html/pages/citizenOffice/citizenOffice.css" />
        <File name="citizenOffice" src="html/pages/citizenOffice/citizenOffice.html" />
        <File name="citizenOffice" src="html/pages/citizenOffice/citizenOffice.js" />
        <File name="furtwangen" src="html/pages/furtwangen/furtwangen.css" />
        <File name="furtwangen" src="html/pages/furtwangen/furtwangen.html" />
        <File name="furtwangen" src="html/pages/furtwangen/furtwangen.js" />
        <File name="games" src="html/pages/games/games.css" />
        <File name="games" src="html/pages/games/games.html" />
        <File name="games" src="html/pages/games/games.js" />
        <File name="gamesCarousel" src="html/pages/games/gamesCarousel.js" />
        <File name="bike" src="html/pages/games/memory/assets/bike.svg" />
        <File name="car" src="html/pages/games/memory/assets/car.svg" />
        <File name="flags" src="html/pages/games/memory/assets/flags.svg" />
        <File name="pawprint" src="html/pages/games/memory/assets/pawprint.svg" />
        <File name="rabbit" src="html/pages/games/memory/assets/rabbit.svg" />
        <File name="tshirt" src="html/pages/games/memory/assets/tshirt.svg" />
        <File name="turtle" src="html/pages/games/memory/assets/turtle.svg" />
        <File name="memory" src="html/pages/games/memory/memory.css" />
        <File name="memory" src="html/pages/games/memory/memory.html" />
        <File name="memory" src="html/pages/games/memory/memory.js" />
        <File name="quiz" src="html/pages/games/quiz/quiz.css" />
        <File name="quiz" src="html/pages/games/quiz/quiz.html" />
        <File name="quiz" src="html/pages/games/quiz/quiz.js" />
        <File name="ticTacToe" src="html/pages/games/ticTacToe/ticTacToe.css" />
        <File name="ticTacToe" src="html/pages/games/ticTacToe/ticTacToe.html" />
        <File name="ticTacToe" src="html/pages/games/ticTacToe/ticTacToe.js" />
        <File name="restaurants" src="html/pages/restaurants/restaurants.css" />
        <File name="restaurants" src="html/pages/restaurants/restaurants.html" />
        <File name="restaurants" src="html/pages/restaurants/restaurants.js" />
        <File name="screenSaver" src="html/pages/screenSaver/screenSaver.css" />
        <File name="screenSaver" src="html/pages/screenSaver/screenSaver.html" />
        <File name="screenSaver" src="html/pages/screenSaver/screenSaver.js" />
        <File name="settings" src="html/pages/settings/settings.css" />
        <File name="settings" src="html/pages/settings/settings.html" />
        <File name="settings" src="html/pages/settings/settings.js" />
        <File name="sport" src="html/pages/sport/sport.css" />
        <File name="sport" src="html/pages/sport/sport.html" />
        <File name="sport" src="html/pages/sport/sport.js" />
        <File name="teamPage" src="html/pages/teamPage/teamPage.css" />
        <File name="teamPage" src="html/pages/teamPage/teamPage.html" />
        <File name="teamPage" src="html/pages/teamPage/teamPage.js" />
        <File name="angular.min" src="html/scripts/angular.min.js" />
        <File name="easterEgg" src="html/scripts/easterEgg.js" />
        <File name="homepage" src="html/scripts/homepage.js" />
        <File name="jquery-2.2.2.min" src="html/scripts/jquery-2.2.2.min.js" />
        <File name="jquery.mobile-1.4.5.min" src="html/scripts/jquery.mobile-1.4.5.min.css" />
        <File name="jquery.mobile-1.4.5.min" src="html/scripts/jquery.mobile-1.4.5.min.js" />
        <File name="jquery.mobile.structure-1.4.5.min" src="html/scripts/jquery.mobile.structure-1.4.5.min.css" />
        <File name="jquery.qimhelpers" src="html/scripts/jquery.qimhelpers.js" />
        <File name="main" src="html/scripts/main.js" />
        <File name="pepperController" src="html/scripts/pepperController.js" />
        <File name="screenSaverTrigger" src="html/scripts/screenSaverTrigger.js" />
        <File name="globals" src="html/styles/globals.css" />
        <File name="main" src="html/styles/main.css" />
        <File name="subpage" src="html/styles/subpage.css" />
        <File name="briefcase" src="html/assets/icons/briefcase.svg" />
        <File name="building_2_circled" src="html/assets/icons/building_2_circled.svg" />
        <File name="building_circled" src="html/assets/icons/building_circled.svg" />
        <File name="document_circled" src="html/assets/icons/document_circled.svg" />
        <File name="hourglass" src="html/assets/icons/hourglass.svg" />
        <File name="info" src="html/assets/icons/info.svg" />
        <File name="love" src="html/assets/icons/love.svg" />
        <File name="mail" src="html/assets/icons/mail.svg" />
        <File name="pause" src="html/assets/icons/pause.svg" />
        <File name="person_3_circled" src="html/assets/icons/person_3_circled.svg" />
        <File name="person_crop_circle_badge_checkmark" src="html/assets/icons/person_crop_circle_badge_checkmark.svg" />
        <File name="phone" src="html/assets/icons/phone.svg" />
        <File name="play" src="html/assets/icons/play.svg" />
        <File name="search" src="html/assets/icons/search.svg" />
        <File name="shield_circled" src="html/assets/icons/shield_circled.svg" />
        <File name="HFU_Furtwangen" src="html/assets/images/HFU_Furtwangen.jpg" />
        <File name="furtwangen_historie" src="html/assets/images/furtwangen_historie.jpg" />
        <File name="furtwangen_restaurant" src="html/assets/images/furtwangen_restaurant.jpg" />
        <File name="furtwangen_wappen" src="html/assets/images/furtwangen_wappen.png" />
        <File name="furtwangenoutdoor" src="html/assets/images/furtwangenoutdoor.jpg" />
        <File name="hfugebaude" src="html/assets/images/hfugebaude.jpg" />
        <File name="hfuwiese" src="html/assets/images/hfuwiese.jpg" />
        <File name="kaffeekuchen" src="html/assets/images/kaffeekuchen.jpg" />
        <File name="skilanglauf" src="html/assets/images/skilanglauf.jpg" />
        <File name="speckplatte" src="html/assets/images/speckplatte.png" />
        <File name="mini_pepper" src="html/assets/mini_pepper.png" />
        <File name="education" src="html/pages/education-page/education.css" />
        <File name="education" src="html/pages/education-page/education.html" />
        <File name="education" src="html/pages/education-page/education.js" />
        <File name="furtwangen-carousel" src="html/pages/furtwangen/furtwangen-carousel.css" />
        <File name="furtwangenCarousel" src="html/pages/furtwangen/furtwangenCarousel.js" />
        <File name="guide" src="html/pages/guide-page/guide.css" />
        <File name="guide" src="html/pages/guide-page/guide.html" />
        <File name="guide" src="html/pages/guide-page/guide.js" />
        <File name="history" src="html/pages/history-page/history.css" />
        <File name="history" src="html/pages/history-page/history.html" />
        <File name="history" src="html/pages/history-page/history.js" />
        <File name="search" src="html/pages/search/search.css" />
        <File name="search" src="html/pages/search/search.html" />
        <File name="search" src="html/pages/search/search.js" />
        <File name="sightseeing" src="html/pages/sightseeing-page/sightseeing.css" />
        <File name="sightseeing" src="html/pages/sightseeing-page/sightseeing.html" />
        <File name="sightseeing" src="html/pages/sightseeing-page/sightseeing.js" />
        <File name="weddingroom" src="html/pages/weddingroom-page/weddingroom.css" />
        <File name="weddingroom" src="html/pages/weddingroom-page/weddingroom.html" />
        <File name="weddingroom" src="html/pages/weddingroom-page/weddingroom.js" />
    </Resources>
    <Topics />
    <IgnoredPaths />
    <Translations auto-fill="de_DE">
        <Translation name="translation_de_DE" src="translations/translation_de_DE.ts" language="de_DE" />
    </Translations>
</Package>
